# Generated by Django 4.2.27 on 2026-02-03 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('nova_score', models.IntegerField(choices=[(1, 'Unprocessed/Minimally Processed'), (2, 'Processed Culinary Ingredients'), (3, 'Processed Foods'), (4, 'Ultra-Processed Foods')], help_text='NOVA food processing classification (1-4)')),
                ('nutri_score', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Moderate'), ('D', 'D - Low'), ('E', 'E - Poor')], help_text='Nutri-Score nutritional rating (A-E)', max_length=1)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit', models.CharField(default='item', help_text="Unit of measurement (e.g., 'item', 'kg', 'litre')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('result_count', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the full CSV was processed')),
            ],
            options={
                'verbose_name': 'Search Query Cache',
                'verbose_name_plural': 'Search Query Caches',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.retailer')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='retailers',
            field=models.ManyToManyField(related_name='products', through='products.ProductPrice', to='products.retailer'),
        ),
        migrations.CreateModel(
            name='OFFProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='EAN/Barcode from Open Food Facts', max_length=50, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('brands', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('nutriscore_grade', models.CharField(choices=[('a', 'A - Excellent'), ('b', 'B - Good'), ('c', 'C - Moderate'), ('d', 'D - Low'), ('e', 'E - Poor'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Nutri-Score nutritional rating (a-e)', max_length=10)),
                ('nova_group', models.IntegerField(blank=True, choices=[(1, 'Unprocessed/Minimally Processed'), (2, 'Processed Culinary Ingredients'), (3, 'Processed Foods'), (4, 'Ultra-Processed Foods')], db_index=True, help_text='NOVA food processing classification (1-4)', null=True)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar content per 100g', max_digits=8, null=True)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Salt content per 100g', max_digits=8, null=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Fat content per 100g', max_digits=8, null=True)),
                ('saturated_fat_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Saturated fat content per 100g', max_digits=8, null=True)),
                ('completeness', models.DecimalField(decimal_places=4, default=0, help_text='Open Food Facts completeness score (0-1)', max_digits=5)),
                ('countries', models.CharField(blank=True, default='', help_text='Countries where product is sold', max_length=500)),
                ('categories', models.TextField(blank=True, default='', help_text='Product categories from OFF')),
                ('search_query', models.CharField(blank=True, db_index=True, default='', help_text='Search query that fetched this product', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this product was last fetched from OFF API')),
            ],
            options={
                'verbose_name': 'OFF Product',
                'verbose_name_plural': 'OFF Products',
                'ordering': ['nutriscore_grade', 'nova_group', 'product_name'],
                'indexes': [models.Index(fields=['nutriscore_grade', 'nova_group'], name='products_of_nutrisc_afd700_idx'), models.Index(fields=['search_query', 'updated_at'], name='products_of_search__208f99_idx'), models.Index(fields=['brands', 'product_name'], name='products_of_brands_8211c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['retailer', 'product'], name='products_pr_retaile_3e3fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'price'], name='products_pr_product_6708aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'retailer')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'nova_score'], name='products_pr_categor_4afb46_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nova_score'], name='products_pr_nova_sc_2f1d52_idx'),
        ),
    ]
