# Generated by Django 4.2.27 on 2026-01-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('nova_score', models.IntegerField(choices=[(1, 'Unprocessed/Minimally Processed'), (2, 'Processed Culinary Ingredients'), (3, 'Processed Foods'), (4, 'Ultra-Processed Foods')], help_text='NOVA food processing classification (1-4)')),
                ('nutri_score', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Moderate'), ('D', 'D - Low'), ('E', 'E - Poor')], help_text='Nutri-Score nutritional rating (A-E)', max_length=1)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit', models.CharField(default='item', help_text="Unit of measurement (e.g., 'item', 'kg', 'litre')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.retailer')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='retailers',
            field=models.ManyToManyField(related_name='products', through='products.ProductPrice', to='products.retailer'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['retailer', 'product'], name='products_pr_retaile_3e3fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'price'], name='products_pr_product_6708aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'retailer')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'nova_score'], name='products_pr_categor_4afb46_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nova_score'], name='products_pr_nova_sc_2f1d52_idx'),
        ),
    ]
