# Generated by Django 4.2.27 on 2026-01-28 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('result_count', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the full CSV was processed')),
            ],
            options={
                'verbose_name': 'Search Query Cache',
                'verbose_name_plural': 'Search Query Caches',
            },
        ),
        migrations.CreateModel(
            name='OFFProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='EAN/Barcode from Open Food Facts', max_length=50, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('brands', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('nutriscore_grade', models.CharField(choices=[('a', 'A - Excellent'), ('b', 'B - Good'), ('c', 'C - Moderate'), ('d', 'D - Low'), ('e', 'E - Poor'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Nutri-Score nutritional rating (a-e)', max_length=10)),
                ('nova_group', models.IntegerField(blank=True, choices=[(1, 'Unprocessed/Minimally Processed'), (2, 'Processed Culinary Ingredients'), (3, 'Processed Foods'), (4, 'Ultra-Processed Foods')], db_index=True, help_text='NOVA food processing classification (1-4)', null=True)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar content per 100g', max_digits=8, null=True)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Salt content per 100g', max_digits=8, null=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Fat content per 100g', max_digits=8, null=True)),
                ('saturated_fat_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Saturated fat content per 100g', max_digits=8, null=True)),
                ('completeness', models.DecimalField(decimal_places=4, default=0, help_text='Open Food Facts completeness score (0-1)', max_digits=5)),
                ('countries', models.CharField(blank=True, default='', help_text='Countries where product is sold', max_length=500)),
                ('categories', models.TextField(blank=True, default='', help_text='Product categories from OFF')),
                ('search_query', models.CharField(blank=True, db_index=True, default='', help_text='Search query that fetched this product', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this product was last fetched from OFF API')),
            ],
            options={
                'verbose_name': 'OFF Product',
                'verbose_name_plural': 'OFF Products',
                'ordering': ['nutriscore_grade', 'nova_group', 'product_name'],
                'indexes': [models.Index(fields=['nutriscore_grade', 'nova_group'], name='products_of_nutrisc_afd700_idx'), models.Index(fields=['search_query', 'updated_at'], name='products_of_search__208f99_idx'), models.Index(fields=['brands', 'product_name'], name='products_of_brands_8211c7_idx')],
            },
        ),
    ]
