# Generated by Django 4.2.27 on 2026-02-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mylistitem_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mylistitem',
            name='products_my_user_id_ce5918_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mylistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mylistitem',
            name='barcode',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mylistitem',
            name='name',
            field=models.CharField(default='tempname', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='mylistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mylistitem',
            name='user',
        ),
    ]
