# Generated by Django 4.2.27 on 2026-03-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_conversation_directmessage_friendship_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='shared_content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='shared_content_type',
            field=models.CharField(blank=True, choices=[('shopping_list', 'Shopping List'), ('recipe', 'Recipe'), ('event', 'Event')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
